### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Frost2006** [TEHE-Studios/ExpandedHelicopterEvents#130]
I had 300+ errors spamming when i lit the flare near a helicopter on top of my house.
and i am using other mods

`function: getDistanceToIsoObject -- file: ExpandedHelicopter01c_MainCore.lua line # 183 | MOD: Expanded Helicopter Events
function: findTarget -- file: ExpandedHelicopter01c_MainCore.lua line # 394 | MOD: Expanded Helicopter Events
function: updateEvent -- file: ExpandedHelicopter01e_MainUpdate.lua line # 29 | MOD: Expanded Helicopter Events
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 303 | MOD: Expanded Helicopter Events
`

`function: getDistanceToIsoObject -- file: ExpandedHelicopter01c_MainCore.lua line # 183 | MOD: Expanded Helicopter Events
function: findTarget -- file: ExpandedHelicopter01c_MainCore.lua line # 394 | MOD: Expanded Helicopter Events
function: updateEvent -- file: ExpandedHelicopter01e_MainUpdate.lua line # 29 | MOD: Expanded Helicopter Events
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 303 | MOD: Expanded Helicopter Events
java.lang.RuntimeException: Object tried to call nil in getDistanceToIsoObject
    at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:973)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
    at zombie.gameStates.IngameState.updateInternal(IngameState.java:1624)
    at zombie.gameStates.IngameState.update(IngameState.java:1333)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by Frost2006** [comment]
oh and this is all the mods im using https://steamcommunity.com/sharedfiles/filedetails/?id=2893725239

**Comment by ChuckTheSheep** [comment]
Addressed with: cda9d91550b8ea6e9265597fc2f2b3b5d03e00b2
