### ISSUE TITLE
Errors when attackheli attacks

### ISSUE THREAD

**Issue by katze1123** [TEHE-Studios/ExpandedHelicopterEvents#139]
**Describe the bug**
Error appears in the right-low corner of the screen while helicopter event attacks. Also i realized I was not getting shooted by the helicopter 

**To Reproduce**
Install the mod and start a new game in a dedicated server. I get the same error on each attack event.

**Expected behavior**
Getting soothed by the helicopter. Not having a error message during the event.

**Screenshots**
None

**Console logs:**
Server Logs Attached
[server-console.txt](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/files/10957266/server-console.txt)

**Comment by HazyLunar** [comment]
Uncertain if this is still an issue for others.
But on my server this happens whenever the attack Heli event begins.

`attempted index: getHealth of non-table: null
function: heliEventAttackHitOnIsoGameCharacter -- file: ExpandedHelicopter04b_AttackOnTarget.lua line # 55 | MOD: Expanded Helicopter Events
function: onServerCommand -- file: ExpandedHelicopter12b_OnServerToClientCommands.lua line # 216 | MOD: Expanded Helicopter Events
java.lang.RuntimeException: attempted index: getHealth of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)
    at zombie.network.GameClient.receiveClientCommand(GameClient.java:1513)
    at zombie.network.PacketTypes$PacketType.onMainLoopHandlePacketInternal(PacketTypes.java:1028)
    at zombie.network.GameClient.mainLoopHandlePacketInternal(GameClient.java:644)
    at zombie.network.GameClient.mainLoopDealWithNetData(GameClient.java:621)
    at zombie.network.GameClient.update(GameClient.java:431)
    at zombie.GameWindow.logic(GameWindow.java:232)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by Chuckleberry-Finn** [comment]
This was fixed here: https://github.com/TEHE-Studios/ExpandedHelicopterEvents/commit/ba72cc91967696d2291c0661dc547334e111f22b
