### ISSUE TITLE
project zomboid expanded helicopter mod

### ISSUE THREAD

**Issue by ZEEzuss** [TEHE-Studios/ExpandedHelicopterEvents#223]
**Describe the bug**

**To Reproduce**

**Expected behavior**
idk im just getting errors
**Screenshots**

**Console logs:**
Console logs are stored in your local files. `OS:\Users\<username>\Zomboid\console.txt`
For single player (or connected players) the file is named `console.txt`, for hosts or servers the file will be named `coop-console` or `server-console`. *Include any relevant logs - do not cut or edit the log to make it smaller.*
`attempted index: addHole of non-table: null
function: heliEventAttackHitOnIsoGameCharacter -- file: ExpandedHelicopter04b_AttackOnTarget.lua line # 100 | MOD: Expanded Helicopter Events
function: onServerCommand -- file: ExpandedHelicopter12b_OnServerToClientCommands.lua line # 226 | MOD: Expanded Helicopter Events
java.lang.RuntimeException: attempted index: addHole of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)
    at zombie.network.GameClient.receiveClientCommand(GameClient.java:1513)
    at zombie.network.PacketTypes$PacketType.onMainLoopHandlePacketInternal(PacketTypes.java:1028)
    at zombie.network.GameClient.mainLoopHandlePacketInternal(GameClient.java:644)
    at zombie.network.GameClient.mainLoopDealWithNetData(GameClient.java:621)
    at zombie.network.GameClient.update(GameClient.java:431)
    at zombie.GameWindow.logic(GameWindow.java:232)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:667)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`
**Additional context**
`attempted index: addHole of non-table: null
function: heliEventAttackHitOnIsoGameCharacter -- file: ExpandedHelicopter04b_AttackOnTarget.lua line # 100 | MOD: Expanded Helicopter Events
function: onServerCommand -- file: ExpandedHelicopter12b_OnServerToClientCommands.lua line # 226 | MOD: Expanded Helicopter Events
java.lang.RuntimeException: attempted index: addHole of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)
    at zombie.network.GameClient.receiveClientCommand(GameClient.java:1513)
    at zombie.network.PacketTypes$PacketType.onMainLoopHandlePacketInternal(PacketTypes.java:1028)
    at zombie.network.GameClient.mainLoopHandlePacketInternal(GameClient.java:644)
    at zombie.network.GameClient.mainLoopDealWithNetData(GameClient.java:621)
    at zombie.network.GameClient.update(GameClient.java:431)
    at zombie.GameWindow.logic(GameWindow.java:232)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:667)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by ZEEzuss** [comment]
this error popped up as soon as i equiped a satchel on my back with a backpack not familiar with coding at all but im not sure why this is giving me an error equipping satchel while wearing a backback on back at same time

**Comment by Chuckleberry-Finn** [comment]
Very odd indeed.

**Comment by ZEEzuss** [comment]
does this mod conflick with expanded backpacks or the journal mod?

**Comment by Chuckleberry-Finn** [comment]
Are you running superbSurvivors or a similar NPC mod?

**Comment by Chuckleberry-Finn** [comment]
Just realized you barely filled the template, and the title of the report is the mod name. lol. Don't worry about it.
