### ISSUE TITLE
ExpandedHelicopter04b_AttackOnTarget.lua line # 62 - attempted index: addHole of non-table: null

### ISSUE THREAD

**Issue by leonskii2** [TEHE-Studios/ExpandedHelicopterEvents#243]
STACK TRACE
-----------------------------------------
function: heliEventAttackHitOnIsoGameCharacter -- file: ExpandedHelicopter04b_AttackOnTarget.lua line # 62 | MOD: Expanded Helicopter Events
function: onServerCommand -- file: ExpandedHelicopter12b_OnServerToClientCommands.lua line # 226 | MOD: Expanded Helicopter Events

ERROR: General     , 1697640504250> 18.696.737.957> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: addHole of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1697640504250> 18.696.737.957> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: addHole of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:173)
	at zombie.network.GameClient.receiveClientCommand(GameClient.java:1513)
	at zombie.network.PacketTypes$PacketType.onMainLoopHandlePacketInternal(PacketTypes.java:1028)
	at zombie.network.GameClient.mainLoopHandlePacketInternal(GameClient.java:644)
	at zombie.network.GameClient.mainLoopDealWithNetData(GameClient.java:621)
	at zombie.network.GameClient.update(GameClient.java:431)
	at zombie.GameWindow.logic(GameWindow.java:232)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:765)
	at zombie.GameWindow.run_ez(GameWindow.java:681)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1697640504252> 18.696.737.959> -----------------------------------------
STACK TRACE

**Comment by leonskii2** [comment]
-----------------------------------------
function: heliEventAttackHitOnIsoGameCharacter -- file: ExpandedHelicopter04b_AttackOnTarget.lua line # 62 | MOD: Expanded Helicopter Events
function: onServerCommand -- file: ExpandedHelicopter12b_OnServerToClientCommands.lua line # 226 | MOD: Expanded Helicopter Events

WARN : Lua         , 1697640505239> 18.696.738.946> LuaManager$GlobalObject.require> require("NVAPI/ctrl/instance") failed
WARN : Lua         , 1697640505585> 18.696.739.291> LuaManager$GlobalObject.require> require("NVAPI/ctrl/instance") failed
WARN : Lua         , 1697640505612> 18.696.739.319> LuaManager$GlobalObject.require> require("NVAPI/ctrl/instance") failed
LOG  : General     , 1697640505651> 18.696.739.357> -------------------------------------------------------------
attempted index: addHole of non-table: null

LOG  : General     , 1697640505651> 18.696.739.358> -----------------------------------------
STACK TRACE
-----------------------------------------

**Comment by leonskii2** [comment]
What is the issue? It apperas right before the helicopter starts shooting.

**Comment by Chuckleberry-Finn** [comment]
Are you able to confirm the version number in the logs?

**Comment by Nightrose2016** [comment]
Just adding my 2 cents cause had the same error game is most recent version and so is mod.  On my private multiplayer server.



```
-----------------------------------------
function: heliEventAttackHitOnIsoGameCharacter -- file: ExpandedHelicopter04b_AttackOnTarget.lua line # 62 | MOD: Expanded Helicopter Events
function: onServerCommand -- file: ExpandedHelicopter12b_OnServerToClientCommands.lua line # 226 | MOD: Expanded Helicopter Events.
[21-10-23 16:12:44.170] LOG  : General     , 1697919164170> 829,295,707> -------------------------------------------------------------
attempted index: addHole of non-table: null.
[21-10-23 16:12:44.171] LOG  : General     , 1697919164171> 829,295,707> -----------------------------------------
STACK TRACE
-----------------------------------------
function: heliEventAttackHitOnIsoGameCharacter -- file: ExpandedHelicopter04b_AttackOnTarget.lua line # 62 | MOD: Expanded Helicopter Events
function: onServerCommand -- file: ExpandedHelicopter12b_OnServerToClientCommands.lua line # 226 | MOD: Expanded Helicopter Events.
[21-10-23 16:12:44.171] ERROR: General     , 1697919164171> 829,295,707> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: addHole of non-table: null at KahluaThread.tableget line:1689..
[21-10-23 16:12:44.171] ERROR: General     , 1697919164171> 829,295,707> DebugLogStream.printException> Stack trace:.
[21-10-23 16:12:44.172] LOG  : General     , 1697919164172> 829,295,708> -----------------------------------------
STACK TRACE
-----------------------------------------
function: heliEventAttackHitOnIsoGameCharacter -- file: ExpandedHelicopter04b_AttackOnTarget.lua line # 62 | MOD: Expanded Helicopter Events
function: onServerCommand -- file: ExpandedHelicopter12b_OnServerToClientCommands.lua line # 226 | MOD: Expanded Helicopter Events.
[21-10-23 16:12:44.979] LOG  : General     , 1697919164979> 829,296,516> -------------------------------------------------------------
attempted index: addHole of non-table: null.
[21-10-23 16:12:44.979] LOG  : General     , 1697919164979> 829,296,516> -----------------------------------------
STACK TRACE
-----------------------------------------
function: heliEventAttackHitOnIsoGameCharacter -- file: ExpandedHelicopter04b_AttackOnTarget.lua line # 62 | MOD: Expanded Helicopter Events
function: onServerCommand -- file: ExpandedHelicopter12b_OnServerToClientCommands.lua line # 226 | MOD: Expanded Helicopter Events.
[21-10-23 16:12:44.980] ERROR: General     , 1697919164980> 829,296,516> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: addHole of non-table: null at KahluaThread.tableget line:1689..
[21-10-23 16:12:44.980] ERROR: General     , 1697919164980> 829,296,517> DebugLogStream.printException> Stack trace:.
[21-10-23 16:12:44.981] LOG  : General     , 1697919164981> 829,296,518> -----------------------------------------
STACK TRACE
```

**Comment by Chuckleberry-Finn** [comment]
Will be fixed next patch.
