### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by moriope** [TEHE-Studios/ExpandedHelicopterEvents#305]
`function: eHeliEvent_ScheduleNew -- file: ExpandedHelicopter06_EventScheduler.lua line # 149 | MOD: Expanded Helicopter Events
function: eHeliEvent_OnHour -- file: ExpandedHelicopter06_EventScheduler.lua line # 300 | MOD: Expanded Helicopter Events
java.lang.RuntimeException: __le not defined for operand
    at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:900)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
    at zombie.gameStates.IngameState.updateInternal(IngameState.java:1624)
    at zombie.gameStates.IngameState.update(IngameState.java:1333)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by Chuckleberry-Finn** [comment]
Looks like a *l*ess than or *e*quals to is failing, but your line numbers don't match up. Please provide the entire console file.

**Comment by Chuckleberry-Finn** [comment]
I don't have an issue like this during tests, and the line numbers don't match up to what your error shows. Without a log I can't resolve the bug.
