### ISSUE TITLE
Here's an error that I got on the supply drop event

### ISSUE THREAD

**Issue by Pinoles17** [TEHE-Studios/ExpandedHelicopterEvents#325]
**Console logs:**
`attempted index: new of non-table: null
function: dropCarePackage -- file: HTC_EHE_ServerHandler.lua line # 41 | MOD: [HERE THEY COME] - Expanded Helicopter Event - Military Drop
function: updateSubFunctions -- file: ExpandedHelicopter01e_MainUpdate.lua line # 259 | MOD: Expanded Helicopter Events
function: updateEvent -- file: ExpandedHelicopter01e_MainUpdate.lua line # 218 | MOD: Expanded Helicopter Events
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 315 | MOD: Expanded Helicopter Events
java.lang.RuntimeException: attempted index: new of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
    at zombie.gameStates.IngameState.updateInternal(IngameState.java:1624)
    at zombie.gameStates.IngameState.update(IngameState.java:1333)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:667)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

**Additional context**
I was on a bulding, in Ravens creek.

![image](https://github.com/TEHE-Studios/ExpandedHelicopterEvents/assets/138397475/416d539b-85d7-43e2-84e9-ad5f8ccb2b8c)

**Comment by Chuckleberry-Finn** [comment]
Seems like the issue is with HTC, and how it's calling the drop.
