### ISSUE TITLE
strange bug

### ISSUE THREAD

**Issue by kristek4** [TEHE-Studios/ExpandedHelicopterEvents#333]
I played with this mod for 1 in-game month and it worked fine until my recent save. During the run, I observed an unusually long loading time. After loading, the game produced 38,000 errors that were increasing exponentially. Every couple of seconds errors were added and frames in the game dropped to 3 fps. the console had the following:

	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1721574952590> -----------------------------------------
STACK TRACE
-----------------------------------------
function: getOrSetPendingSpawnsList -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 61 | MOD: Expanded Helicopter Events
function: parseSquare -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 228 | MOD: Expanded Helicopter Events

LOG  : General     , 1721574952590> -----------------------------------------
STACK TRACE
-----------------------------------------
function: getOrSetPendingSpawnsList -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 61 | MOD: Expanded Helicopter Events
function: parseSquare -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 228 | MOD: Expanded Helicopter Events

ERROR: General     , 1721574952590> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: Object tried to call nil in getOrSetPendingSpawnsList at KahluaUtil.fail line:82.
ERROR: General     , 1721574952590> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: Object tried to call nil in getOrSetPendingSpawnsList
	at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:973)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
	at zombie.iso.IsoChunk.doLoadGridsquare(IsoChunk.java:3333)
	at zombie.iso.IsoChunkMap.update(IsoChunkMap.java:199)
	at zombie.iso.IsoCell.updateInternal(IsoCell.java:5735)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.iso.IsoCell.update(IsoCell.java:5696)
	at zombie.iso.IsoWorld.updateInternal(IsoWorld.java:3499)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.iso.IsoWorld.update(IsoWorld.java:3427)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1617)
	at zombie.gameStates.IngameState.update(IngameState.java:1333)
	at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
	at zombie.GameWindow.logic(GameWindow.java:298)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:765)
	at zombie.GameWindow.run_ez(GameWindow.java:667)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1721574952591> -----------------------------------------
STACK TRACE
-----------------------------------------
function: getOrSetPendingSpawnsList -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 61 | MOD: Expanded Helicopter Events
function: parseSquare -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 228 | MOD: Expanded Helicopter Events

LOG  : General     , 1721574953927> EXITDEBUG: ToggleEscapeMenu 1
LOG  : General     , 1721574953927> EXITDEBUG: ToggleEscapeMenu 3
LOG  : General     , 1721574953927> EXITDEBUG: ToggleEscapeMenu 4
LOG  : General     , 1721574953927> EXITDEBUG: ToggleEscapeMenu 5
LOG  : General     , 1721574953927> EXITDEBUG: setGameSpeed 1
LOG  : General     , 1721574953928> EXITDEBUG: setGameSpeed 3
LOG  : General     , 1721574953928> EXITDEBUG: setShowPausedMessage 1
LOG  : General     , 1721574953928> EXITDEBUG: setShowPausedMessage 2
LOG  : General     , 1721574953939> ECC: OnKeyPressed Hillary

p.s. there was no point in inserting all the text because it was repeated

**Comment by Chuckleberry-Finn** [comment]
Thank you.
